### PR TITLE
Fix peer list bugs for benchmarking

### LINKED ISSUE #70: Benchmark with --peer-list returns an error
Error saying cannot specify peer using `--peer` and `--peer-list`.

### PR DESCRIPTION
**Pull request by prashantv**
Peer-list was ignoring the last line if it did not end with a "\n"
Benchmark warmup failed if --peer-list was used (introduced in
round-robin peer selection, #61).

Fixes #70

### CODE REVIEW

File: main_test.go [hunk 1]
```diff
@@ -213,6 +214,33 @@ func TestHealthIntegration(t *testing.T) {
 	main()
 }
 
+func TestBenchmarkIntegration(t *testing.T) {
+	origArgs := os.Args
+	defer func() { os.Args = origArgs }()
+
+	const numServers = 5
```
Comment (abhinav) [inline main_test.go]: Why make this a constant here? It's not used anywhere else. Just for readability?

Comment (prashantv) [inline main_test.go]: Yeah just for readability

**Comment by abhinav** [comment]
👍
